### ISSUE TITLE
big performance issue

### ISSUE THREAD

**Issue by CowWorks** [Soofiaaa/Atomic#1]
i am sorry to inform you that this cheat is really low performing. today, as i was about to use it to cheat on my favorite competitive multiplayer game, i decided to take atomic out for a test run, as i loaded into the lobby, i realized that my fps was really low, i'm talking over 50 fps. i would enjoy if you could fix it and for example write it in C++. thank you^^

**Comment by TheCaffeineCode** [comment]
Don't use this cheat, get superior software at https://adrenalin.win/

**Comment by CowWorks** [comment]
> Don't use this cheat, get superior software at https://adrenalin.win/

thank you for this suggestion! i tried it and it was very high performant 👍

**Comment by TheCaffeineCode** [comment]
> thank you for this suggestion! i tried it and it was very high performant 👍

No problem, just a reminder that V4 is greater than anything our competitors will put out!
