### ISSUE TITLE
big cheat issue

### ISSUE THREAD

**Issue by TheCaffeineCode** [Soofiaaa/Atomic#2]
when i use this cheat i feel sad. the lack of a ragebot, competent esp code, misc features or anything modern in a csgo cheat leaves me feeling empty inside. please fix these issues by writing the cheat from scratch and in C++, or just get a better cheat at https://adrenalin.win

**Comment by JokersCat** [comment]
I think this project is just for fun and should not be a cheat to win every hvh it only should show how game injections in Python work and for this it is awesome 😊

**Comment by TheCaffeineCode** [comment]
Nah

> I think this project is just for fun and should not be a cheat to win every hvh it only should show how game injections in Python work and for this it is awesome 😊

**Comment by JokersCat** [comment]
Why do you think so do you really think that he/she wanted to create a high Level csgo cheat? 😂 I mean Python is not meant to do something like this.But it is cool to see what People can do with it

**Comment by TheCaffeineCode** [comment]
> Why do you think so do you really think that he/she wanted to create a high Level csgo cheat? 😂 I mean Python is not meant to do something like this.But it is cool to see what People can do with it

Nah. Adrenalin' on top

**Comment by JokersCat** [comment]
Uhm okay 😂

**Comment by TheCaffeineCode** [comment]
> Uhm okay 😂

Exactly. All hail Adrenalin' V4.
